@props([
    "user",
    "userInformation",
    "isViewTo" => false,
])
@php
    $options_gender = [
        __('Male') => "male",
        __('Female') => "female",
    ];
    $countries = [
        __('Select Country') => "",
        "Afghanistan"       => "afghanistan",
        "Albania"           => "albania",
        "Algeria"           => "algeria",
        "Andorra"           => "andorra",
        "Angola"            => "angola",
        "Argentina"         => "argentina",
        "Armenia"           => "armenia",
        "Australia"         => "australia",
        "Austria"           => "austria",
        "Azerbaijan"        => "azerbaijan",
        "Bahamas"           => "bahamas",
        "Bahrain"           => "bahrain",
        "Bangladesh"        => "bangladesh",
        "Barbados"          => "barbados",
        "Belarus"           => "belarus",
        "Belgium"           => "belgium",
        "Belize"            => "belize",
        "Benin"             => "benin",
        "Bhutan"            => "bhutan",
        "Bolivia"           => "bolivia",
        "Bosnia and Herzegovina" => "bosnia and herzegovina",
        "Botswana"          => "botswana",
        "Brazil"            => "brazil",
        "Brunei"            => "brunei",
        "Bulgaria"          => "bulgaria",
        "Burkina Faso"      => "burkina faso",
        "Burundi"           => "burundi",
        "Cambodia"          => "cambodia",
        "Cameroon"          => "cameroon",
        "Canada"            => "canada",
        "Cape Verde"        => "cape verde",
        "Central African Republic" => "central african republic",
        "Chad"              => "chad",
        "Chile"             => "chile",
        "China"             => "china",
        "Colombia"          => "colombia",
        "Comoros"           => "comoros",
        "Congo (Republic)"  => "congo (republic)",
    "Congo (Democratic Republic)" => "congo (democratic republic)",
    "Costa Rica"        => "costa rica",
    "Croatia"           => "croatia",
    "Cuba"              => "cuba",
    "Cyprus"            => "cyprus",
    "Czechia"           => "czechia",
    "Denmark"           => "denmark",
    "Djibouti"          => "djibouti",
    "Dominica"          => "dominica",
    "Dominican Republic" => "dominican republic",
    "Ecuador"           => "ecuador",
    "Egypt"             => "egypt",
    "El Salvador"       => "el salvador",
    "Equatorial Guinea" => "equatorial guinea",
    "Eritrea"           => "eritrea",
    "Estonia"           => "estonia",
    "Eswatini"           => "eswatini",
    "Ethiopia"          => "ethiopia",
    "Fiji"              => "fiji",
    "Finland"           => "finland",
    "France"            => "france",
    "Gabon"             => "gabon",
    "Gambia"            => "gambia",
    "Georgia"           => "georgia",
    "Germany"           => "germany",
    "Ghana"             => "ghana",
    "Greece"            => "greece",
    "Grenada"           => "grenada",
    "Guatemala"         => "guatemala",
    "Guinea"            => "guinea",
    "Guinea-Bissau"     => "guinea-bissau",
    "Guyana"            => "guyana",
    "Haiti"             => "haiti",
    "Honduras"          => "honduras",
    "Hungary"           => "hungary",
    "Iceland"           => "iceland",
    "India"             => "india",
    "Indonesia"         => "indonesia",
    "Iran"              => "iran",
    "Iraq"              => "iraq",
    "Ireland"           => "ireland",
    "Israel"            => "israel",
    "Italy"             => "italy",
    "Jamaica"           => "jamaica",
    "Japan"             => "japan",
    "Jordan"            => "jordan",
    "Kazakhstan"        => "kazakhstan",
    "Kenya"             => "kenya",
    "Kiribati"          => "kiribati",
    "Kuwait"            => "kuwait",
    "Kyrgyzstan"        => "kyrgyzstan",
    "Laos"              => "laos",
    "Latvia"            => "latvia",
    "Lebanon"           => "lebanon",
    "Lesotho"           => "lesotho",
    "Liberia"           => "liberia",
    "Libya"             => "libya",
    "Liechtenstein"     => "liechtenstein",
    "Lithuania"         => "lithuania",
    "Luxembourg"        => "luxembourg",
    "Madagascar"        => "madagascar",
    "Malawi"            => "malawi",
    "Malaysia"          => "malaysia",
    "Maldives"          => "maldives",
    "Mali"              => "mali",
    "Malta"             => "malta",
    "Marshall Islands"  => "marshall islands",
    "Mauritania"        => "mauritania",
    "Mauritius"         => "mauritius",
    "Mexico"            => "mexico",
    "Micronesia"        => "micronesia",
    "Moldova"           => "moldova",
    "Monaco"            => "monaco",
    "Mongolia"          => "mongolia",
    "Montenegro"        => "montenegro",
    "Morocco"           => "morocco",
    "Mozambique"        => "mozambique",
    "Myanmar"           => "myanmar",
    "Namibia"           => "namibia",
    "Nauru"             => "nauru",
    "Nepal"             => "nepal",
    "Netherlands"       => "netherlands",
    "New Zealand"       => "new zealand",
    "Nicaragua"         => "nicaragua",
    "Niger"             => "niger",
    "Nigeria"           => "nigeria",
    "North Korea"       => "north korea",
    "North Macedonia"   => "north macedonia",
    "Norway"            => "norway",
    "Oman"              => "oman",
    "Palestine"         => "palestine",
    "Pakistan"          => "pakistan",
    "Palau"             => "palau",
    "Panama"            => "panama",
    "Papua New Guinea"  => "papua new guinea",
    "Paraguay"          => "paraguay",
    "Peru"              => "peru",
    "Philippines"        => "philippines",
    "Poland"            => "poland",
    "Portugal"          => "portugal",
    "Qatar"             => "qatar",
    "Romania"           => "romania",
    "Russia"            => "russia",
    "Rwanda"            => "rwanda",
    "Saint Kitts and Nevis" => "saint kitts and nevis",
    "Saint Lucia"       => "saint lucia",
    "Saint Vincent and the Grenadines" => "saint vincent and the grenadines",
    "Samoa"             => "samoa",
    "San Marino"        => "san marino",
    "Sao Tome and Principe" => "sao tome and principe",
    "Saudi Arabia"      => "saudi arabia",
    "Senegal"           => "senegal",
    "Serbia"            => "serbia",
    "Seychelles"        => "seychelles",
    "Sierra Leone"      => "sierra leone",
    "Singapore"         => "singapore",
    "Slovakia"          => "slovakia",
    "Slovenia"          => "slovenia",
    "Solomon Islands"   => "solomon islands",
    "Somalia"           => "somalia",
    "South Africa"      => "south africa",
    "South Korea"       => "south korea",
    "South Sudan"       => "south sudan",
    "Spain"             => "spain",
    "Sri Lanka"         => "sri lanka",
    "Sudan"             => "sudan",
    "Suriname"          => "suriname",
    "Sweden"            => "sweden",
    "Switzerland"       => "switzerland",
    "Syria"             => "syria",
    "Taiwan"            => "taiwan",
    "Tajikistan"        => "tajikistan",
    "Tanzania"          => "tanzania",
    "Thailand"          => "thailand",
    "Timor-Leste"       => "timor-leste",
    "Togo"              => "togo",
    "Tonga"             => "tonga",
    "Trinidad and Tobago" => "trinidad and tobago",
    "Tunisia"           => "tunisia",
    "Turkey"            => "turkey",
    "Turkmenistan"      => "turkmenistan",
    "Tuvalu"            => "tuvalu",
    "Uganda"            => "uganda",
    "Ukraine"           => "ukraine",
    "United Arab Emirates" => "united arab emirates",
    "United Kingdom"    => "united kingdom",
    "United States"     => "united states",
    "Uruguay"           => "uruguay",
    "Uzbekistan"        => "uzbekistan",
    "Vanuatu"           => "vanuatu",
    "Vatican City"      => "vatican city",
    "Venezuela"         => "venezuela",
    "Vietnam"           => "vietnam",
    "Yemen"             => "yemen",
    "Zambia"            => "zambia",
    "Zimbabwe"          => "zimbabwe",
    "Kosovo"            => "kosovo",
    "Western Sahara"    => "western sahara",
    "Abkhazia"          => "abhkhazia",
    "South Ossetia"     => "south ossetia",
    "Transnistria"      => "transnistria",
    "Somaliland"        => "somaliland",
    "Nagorno-Karabakh"  => "nagorno-karabakh",
    "Northern Cyprus"   => "northern cyprus",
];
@endphp

@if($isViewTo == false)
    <div @if($errors->hasAny('name' , 'email' , 'phone_number' , 'date_pirth' , 'gender' , 'address' , 'occupation' , 'link_one' , 'link_two' , 'link_three' , 'link_one_as' , 'link_two_as' , 'link_three_as')) class="w-full h-fit mt-6 p-5 border border-violet-500 rounded-md" @else class="hidden w-full h-fit mt-6 p-5 border border-violet-500 rounded-md" @endif id="form_edit_overview">
        <x-form-structure action="{{route('profile.cv.overview')}}" buttonClass="w-full h-fit rounded-xl bg-violet-300 flex justify-center items-center p-3 mt-5" buttonClassChiled="fill-white" formClass="w-full h-fit flex flex-col justify-center items-center p-6">
            @if($userInformation->photo ?? null)
                <x-form-fieldset-file name="photo" fieldsetClass="w-full h-fit">
                        <a href="{{route('utilities.viewFile' , ['App\\Models\\Information' , $userInformation->id , 'photo' , 'false' , 'null' , 'false'])}}" target="_blank" class="text-blue-600 hover:text-blue-800 hover:underline">View Previous Photo</a>
                </x-form-fieldset-file>
            @else
                <x-form-fieldset-file name="photo" fieldsetClass="w-full h-fit"/>
            @endif
            <x-form-fieldset name="name" type="text" value="{{$user->name ?? old('name')}}" lableName="{{ __('Name') }}" placeholder="{{ __('Name') }}" fieldsetClass="w-full h-fit"/>
            <x-form-fieldset name="email" type="email" value="{{$userInformation->email ?? old('email')}}" lableName="{{ __('Email') }}" placeholder="{{ __('Email') }}" fieldsetClass="w-full h-fit"/>
            <x-form-fieldset name="phone_number" type="tel" value="{{$user->phone_number ?? old('phone_number')}}" lableName="{{ __('Phone Number') }}" placeholder="{{ __('Phone Number') }}" fieldsetClass="w-full h-fit"/>
            <x-form-fieldset name="date_pirth" type="date" value="{{$userInformation->date_pirth ?? old('date_pirth')}}" lableName="{{ __('Date Pirth') }}" placeholder="{{ __('Date Pirth') }}" fieldsetClass="w-full h-fit"/>
            <x-form-fieldset-select name="gender" value="{{$userInformation->gender ?? old('gender')}}" :options="$options_gender" lableName="{{ __('Gender') }}" placeholder="{{ __('Gender') }}" fieldsetClass="w-full h-fit"/>
            <x-form-fieldset-select name="address" type="" value="{{$userInformation->address ?? old('address')}}" :options="$countries" lableName="{{ __('Address') }}" placeholder="{{ __('Address') }}" fieldsetClass="w-full h-fit"/>
            <x-form-fieldset name="occupation" type="text" value="{{$userInformation->occupation ?? old('occupation')}}" lableName="{{ __('Occupation') }}" placeholder="{{ __('Occupation') }}" fieldsetClass="w-full h-fit"/>
            <div class="w-full h-fit grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
                <x-form-fieldset name="link_one" type="url" value="{{$userInformation->link_one ?? old('link_one')}}" lableName="{{ __('Link One') }}" placeholder="{{ __('Link One') }}" fieldsetClass="w-full"/>
                <x-form-fieldset name="link_two" type="url" value="{{$userInformation->link_two ?? old('link_two')}}" lableName="{{ __('Link Two') }}" placeholder="{{ __('Link Two') }}" fieldsetClass="w-full"/>
                <x-form-fieldset name="link_three" type="url" value="{{$userInformation->link_three ?? old('link_three')}}" lableName="{{ __('Link Three') }}" placeholder="{{ __('Link Three') }}" fieldsetClass="w-full"/>
                <x-form-fieldset name="link_one_as" type="text" value="{{$userInformation->link_one_as ?? old('link_one_as')}}" lableName="{{ __('Link One As') }}" placeholder="{{ __('Link One As') }}" fieldsetClass="w-full"/>
                <x-form-fieldset name="link_two_as" type="text" value="{{$userInformation->link_two_as ?? old('link_two_as')}}" lableName="{{ __('Link Two As') }}" placeholder="{{ __('Link Two As') }}" fieldsetClass="w-full"/>
                <x-form-fieldset name="link_three_as" type="text" value="{{$userInformation->link_three_as ?? old('link_three_as')}}" lableName="{{ __('Link Three As') }}" placeholder="{{ __('Link Three As') }}" fieldsetClass="w-full"/>
            </div>
        </x-form-structure>
    </div>
@endif
